=== BOBO41/trifolia/Trifolia.Terminology/Transforms/oid_mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2015 sp2 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="root" type="T_root"/>
	<xs:element name="convert" type="T_convert"/>
	<xs:attribute name="oid" type="AT_1"/>
	<xs:attribute name="uri" type="xs:anyURI"/>
	<xs:complexType name="T_root">
		<xs:sequence>
			<xs:element ref="convert" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_convert">
		<xs:attribute ref="oid" use="required"/>
		<xs:attribute ref="uri" use="required"/>
	</xs:complexType>
	<xs:simpleType name="AT_1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="2.16.840.1.113883.1.3"/>
			<xs:enumeration value="2.16.840.1.113883.3.117"/>
			<xs:enumeration value="2.16.840.1.113883.3.2819"/>
			<xs:enumeration value="2.16.840.1.113883.4.1"/>
			<xs:enumeration value="2.16.840.1.113883.5.1"/>
			<xs:enumeration value="2.16.840.1.113883.5.10"/>
			<xs:enumeration value="2.16.840.1.113883.5.100"/>
			<xs:enumeration value="2.16.840.1.113883.5.1001"/>
			<xs:enumeration value="2.16.840.1.113883.5.1002"/>
			<xs:enumeration value="2.16.840.1.113883.5.1008"/>
			<xs:enumeration value="2.16.840.1.113883.5.1009"/>
			<xs:enumeration value="2.16.840.1.113883.5.101"/>
			<xs:enumeration value="2.16.840.1.113883.5.1010"/>
			<xs:enumeration value="2.16.840.1.113883.5.1017"/>
			<xs:enumeration value="2.16.840.1.113883.5.102"/>
			<xs:enumeration value="2.16.840.1.113883.5.1020"/>
			<xs:enumeration value="2.16.840.1.113883.5.1022"/>
			<xs:enumeration value="2.16.840.1.113883.5.103"/>
			<xs:enumeration value="2.16.840.1.113883.5.105"/>
			<xs:enumeration value="2.16.840.1.113883.5.1050"/>
			<xs:enumeration value="2.16.840.1.113883.5.1055"/>
			<xs:enumeration value="2.16.840.1.113883.5.1056"/>
			<xs:enumeration value="2.16.840.1.113883.5.1057"/>
			<xs:enumeration value="2.16.840.1.113883.5.106"/>
			<xs:enumeration value="2.16.840.1.113883.5.1061"/>
			<xs:enumeration value="2.16.840.1.113883.5.1062"/>
			<xs:enumeration value="2.16.840.1.113883.5.1067"/>
			<xs:enumeration value="2.16.840.1.113883.5.1068"/>
			<xs:enumeration value="2.16.840.1.113883.5.1069"/>
			<xs:enumeration value="2.16.840.1.113883.5.107"/>
			<xs:enumeration value="2.16.840.1.113883.5.1074"/>
			<xs:enumeration value="2.16.840.1.113883.5.108"/>
			<xs:enumeration value="2.16.840.1.113883.5.1082"/>
			<xs:enumeration value="2.16.840.1.113883.5.109"/>
			<xs:enumeration value="2.16.840.1.113883.5.1092"/>
			<xs:enumeration value="2.16.840.1.113883.5.1097"/>
			<xs:enumeration value="2.16.840.1.113883.5.1099"/>
			<xs:enumeration value="2.16.840.1.113883.5.110"/>
			<xs:enumeration value="2.16.840.1.113883.5.1100"/>
			<xs:enumeration value="2.16.840.1.113883.5.111"/>
			<xs:enumeration value="2.16.840.1.113883.5.1111"/>
			<xs:enumeration value="2.16.840.1.113883.5.1116"/>
			<xs:enumeration value="2.16.840.1.113883.5.1117"/>
			<xs:enumeration value="2.16.840.1.113883.5.1119"/>
			<xs:enumeration value="2.16.840.1.113883.5.1120"/>
			<xs:enumeration value="2.16.840.1.113883.5.1121"/>
			<xs:enumeration value="2.16.840.1.113883.5.1122"/>
			<xs:enumeration value="2.16.840.1.113883.5.1124"/>
			<xs:enumeration value="2.16.840.1.113883.5.1126"/>
			<xs:enumeration value="2.16.840.1.113883.5.1129"/>
			<xs:enumeration value="2.16.840.1.113883.5.113"/>
			<xs:enumeration value="2.16.840.1.113883.5.1137"/>
			<xs:enumeration value="2.16.840.1.113883.5.12"/>
			<xs:enumeration value="2.16.840.1.113883.5.13"/>
			<xs:enumeration value="2.16.840.1.113883.5.139"/>
			<xs:enumeration value="2.16.840.1.113883.5.14"/>
			<xs:enumeration value="2.16.840.1.113883.5.143"/>
			<xs:enumeration value="2.16.840.1.113883.5.16"/>
			<xs:enumeration value="2.16.840.1.113883.5.18"/>
			<xs:enumeration value="2.16.840.1.113883.5.2"/>
			<xs:enumeration value="2.16.840.1.113883.5.21"/>
			<xs:enumeration value="2.16.840.1.113883.5.25"/>
			<xs:enumeration value="2.16.840.1.113883.5.30"/>
			<xs:enumeration value="2.16.840.1.113883.5.4"/>
			<xs:enumeration value="2.16.840.1.113883.5.41"/>
			<xs:enumeration value="2.16.840.1.113883.5.43"/>
			<xs:enumeration value="2.16.840.1.113883.5.44"/>
			<xs:enumeration value="2.16.840.1.113883.5.45"/>
			<xs:enumeration value="2.16.840.1.113883.5.57"/>
			<xs:enumeration value="2.16.840.1.113883.5.6"/>
			<xs:enumeration value="2.16.840.1.113883.5.79"/>
			<xs:enumeration value="2.16.840.1.113883.5.81"/>
			<xs:enumeration value="2.16.840.1.113883.5.9"/>
			<xs:enumeration value="2.16.840.1.113883.5.90"/>
			<xs:enumeration value="2.16.840.1.113883.6.1"/>
			<xs:enumeration value="2.16.840.1.113883.6.121"/>
			<xs:enumeration value="2.16.840.1.113883.6.256"/>
			<xs:enumeration value="2.16.840.1.113883.6.3"/>
			<xs:enumeration value="2.16.840.1.113883.6.42"/>
			<xs:enumeration value="2.16.840.1.113883.6.73"/>
			<xs:enumeration value="2.16.840.1.113883.6.8"/>
			<xs:enumeration value="2.16.840.1.113883.6.96"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== BOBO41/trifolia/Trifolia.Terminology/Transforms/oid_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/rickg/Documents/Lantana/projects/HL7/IGs/CDAR2_QRDA_DSTUR2_2012JUL/Updated_CDA_Schema_Files_Extension_Support/CDA_Schema_Files/infrastructure/cda/oid_mapping.xsd">
	<!-- Common ID Assigning Authorities -->
	<convert oid="2.16.840.1.113883.3.117" uri="http://www.lantanagroup.com"/>
	<convert oid="2.16.840.1.113883.4.1" uri="http://hl7.org/fhir/sid/us-ssn"/>
	<convert oid="2.16.840.1.113883.3.2819" uri="http://www.axesson.com"/>
	<!-- need to add SSN, state driver licenses, etc. -->
	<!-- External (to HL7) Code Systems -->
	<convert oid="2.16.840.1.113883.1.3" uri="http://HL7 Registered RMIMs"/>
	<convert oid="2.16.840.1.113883.6.1" uri="http://loinc.org"/>
	<convert oid="2.16.840.1.113883.6.3" uri="http://hl7.org/fhir/sid/icd-10"/>
	<convert oid="2.16.840.1.113883.6.8" uri="http://unitsofmeasure.org"/>
	<convert oid="2.16.840.1.113883.6.42" uri="http://hl7.org/fhir/sid/icd-9"/>
	<convert oid="2.16.840.1.113883.6.73" uri="http://www.whocc.no/atc"/>
	<convert oid="2.16.840.1.113883.6.96" uri="http://snomed.info/sct"/>
	<convert oid="2.16.840.1.113883.6.256" uri="http://www.radlex.org/"/>
	<!-- Internal (to HL7) Code Systems -->
	<convert oid="2.16.840.1.113883.5.25" uri="http://fhir.org.nz/xds#confidentiality"/>
	<convert oid="2.16.840.1.113883.5.1050" uri="http://hl7.org/fhir/v3/AcknowledgementCondition"/>
	<convert oid="2.16.840.1.113883.5.1100" uri="http://hl7.org/fhir/v3/AcknowledgementDetailCode"/>
	<convert oid="2.16.840.1.113883.5.1082" uri="http://hl7.org/fhir/v3/AcknowledgementDetailType"/>
	<convert oid="2.16.840.1.113883.5.18" uri="http://hl7.org/fhir/v3/AcknowledgementType"/>
	<convert oid="2.16.840.1.113883.5.6" uri="http://hl7.org/fhir/v3/ActClass"/>
	<convert oid="2.16.840.1.113883.5.1" uri="http://hl7.org/fhir/v3/AdministrativeGender"/>
	<convert oid="2.16.840.1.113883.5.4" uri="http://hl7.org/fhir/v3/ActCode"/>
	<convert oid="2.16.840.1.113883.5.1001" uri="http://hl7.org/fhir/v3/ActMood"/>
	<convert oid="2.16.840.1.113883.5.10" uri="http://hl7.org/fhir/v3/ActRelationshipCheckpoint"/>
	<convert oid="2.16.840.1.113883.5.12" uri="http://hl7.org/fhir/v3/ActRelationshipJoin"/>
	<convert oid="2.16.840.1.113883.5.13" uri="http://hl7.org/fhir/v3/ActRelationshipSplit"/>
	<convert oid="2.16.840.1.113883.5.1099" uri="http://hl7.org/fhir/v3/ActRelationshipSubset"/>
	<convert oid="2.16.840.1.113883.5.1002" uri="http://hl7.org/fhir/v3/ActRelationshipType"/>
	<convert oid="2.16.840.1.113883.5.14" uri="http://hl7.org/fhir/v3/ActStatus"/>
	<convert oid="2.16.840.1.113883.5.16" uri="http://hl7.org/fhir/v3/AddressPartType"/>
	<convert oid="2.16.840.1.113883.5.1119" uri="http://hl7.org/fhir/v3/AddressUse"/>
	<convert oid="2.16.840.1.113883.5.1055" uri="http://hl7.org/fhir/v3/Calendar"/>
	<convert oid="2.16.840.1.113883.5.9" uri="http://hl7.org/fhir/v3/CalendarCycle"/>
	<convert oid="2.16.840.1.113883.5.1017" uri="http://hl7.org/fhir/v3/CalendarType"/>
	<convert oid="2.16.840.1.113883.5.21" uri="http://hl7.org/fhir/v3/Charset"/>
	<convert oid="2.16.840.1.113883.5.1074" uri="http://hl7.org/fhir/v3/CodingRationale"/>
	<convert oid="2.16.840.1.113883.5.1056" uri="http://hl7.org/fhir/v3/CommunicationFunctionType"/>
	<convert oid="2.16.840.1.113883.5.1009" uri="http://hl7.org/fhir/v3/CompressionAlgorithm"/>
	<convert oid="2.16.840.1.113883.5.25" uri="http://hl7.org/fhir/v3/Confidentiality"/>
	<convert oid="2.16.840.1.113883.5.1057" uri="http://hl7.org/fhir/v3/ContextControl"/>
	<convert oid="2.16.840.1.113883.5.41" uri="http://hl7.org/fhir/v3/EntityClass"/>
	<convert oid="2.16.840.1.113883.5.30" uri="http://hl7.org/fhir/v3/EntityDeterminer"/>
	<convert oid="2.16.840.1.113883.5.43" uri="http://hl7.org/fhir/v3/EntityNamePartQualifier"/>
	<convert oid="2.16.840.1.113883.5.1122" uri="http://hl7.org/fhir/v3/EntityNamePartQualifierR2"/>
	<convert oid="2.16.840.1.113883.5.44" uri="http://hl7.org/fhir/v3/EntityNamePartType"/>
	<convert oid="2.16.840.1.113883.5.1121" uri="http://hl7.org/fhir/v3/EntityNamePartTypeR2"/>
	<convert oid="2.16.840.1.113883.5.45" uri="http://hl7.org/fhir/v3/EntityNameUse"/>
	<convert oid="2.16.840.1.113883.5.1120" uri="http://hl7.org/fhir/v3/EntityNameUseR2"/>
	<convert oid="2.16.840.1.113883.5.1061" uri="http://hl7.org/fhir/v3/EntityStatus"/>
	<convert oid="2.16.840.1.113883.5.1022" uri="http://hl7.org/fhir/v3/GTSAbbreviation"/>
	<convert oid="2.16.840.1.113883.5.1129" uri="http://hl7.org/fhir/v3/HL7ContextConductionStyle"/>
	<convert oid="2.16.840.1.113883.5.1092" uri="http://hl7.org/fhir/v3/hl7ITSVersionCode"/>
	<convert oid="2.16.840.1.113883.5.1124" uri="http://hl7.org/fhir/v3/hl7Realm"/>
	<convert oid="2.16.840.1.113883.5.1097" uri="http://hl7.org/fhir/v3/HL7StandardVersionCode"/>
	<convert oid="2.16.840.1.113883.5.57" uri="http://hl7.org/fhir/v3/HL7UpdateMode"/>
	<convert oid="2.16.840.1.113883.5.1117" uri="http://hl7.org/fhir/v3/IdentifierReliability"/>
	<convert oid="2.16.840.1.113883.5.1116" uri="http://hl7.org/fhir/v3/IdentifierScope"/>
	<convert oid="2.16.840.1.113883.6.121" uri="http://hl7.org/fhir/v3/ietf3066"/>
	<convert oid="2.16.840.1.113883.5.1010" uri="http://hl7.org/fhir/v3/IntegrityCheckAlgorithm"/>
	<convert oid="2.16.840.1.113883.5.1062" uri="http://hl7.org/fhir/v3/ManagedParticipationStatus"/>
	<convert oid="2.16.840.1.113883.5.2" uri="http://hl7.org/fhir/v3/MaritalStatus"/>
	<convert oid="2.16.840.1.113883.5.79" uri="http://hl7.org/fhir/v3/mediaType"/>
	<convert oid="2.16.840.1.113883.5.81" uri="http://hl7.org/fhir/v3/ModifyIndicator"/>
	<convert oid="2.16.840.1.113883.5.1008" uri="http://hl7.org/fhir/v3/NullFlavor"/>
	<convert oid="2.16.840.1.113883.5.90" uri="http://hl7.org/fhir/v3/ParticipationType"/>
	<convert oid="2.16.840.1.113883.5.1020" uri="http://hl7.org/fhir/v3/ProbabilityDistributionType"/>
	<convert oid="2.16.840.1.113883.5.100" uri="http://hl7.org/fhir/v3/ProcessingID"/>
	<convert oid="2.16.840.1.113883.5.101" uri="http://hl7.org/fhir/v3/ProcessingMode"/>
	<convert oid="2.16.840.1.113883.5.102" uri="http://hl7.org/fhir/v3/QueryPriority"/>
	<convert oid="2.16.840.1.113883.5.1067" uri="http://hl7.org/fhir/v3/QueryResponse"/>
	<convert oid="2.16.840.1.113883.5.103" uri="http://hl7.org/fhir/v3/QueryStatusCode"/>
	<convert oid="2.16.840.1.113883.5.105" uri="http://hl7.org/fhir/v3/RelationalOperator"/>
	<convert oid="2.16.840.1.113883.5.106" uri="http://hl7.org/fhir/v3/RelationshipConjunction"/>
	<convert oid="2.16.840.1.113883.5.108" uri="http://hl7.org/fhir/v3/ResponseLevel"/>
	<convert oid="2.16.840.1.113883.5.109" uri="http://hl7.org/fhir/v3/ResponseModality"/>
	<convert oid="2.16.840.1.113883.5.1126" uri="http://hl7.org/fhir/v3/ResponseMode"/>
	<convert oid="2.16.840.1.113883.5.110" uri="http://hl7.org/fhir/v3/RoleClass"/>
	<convert oid="2.16.840.1.113883.5.111" uri="http://hl7.org/fhir/v3/RoleCode"/>
	<convert oid="2.16.840.1.113883.5.1137" uri="http://hl7.org/fhir/v3/RoleLinkStatus"/>
	<convert oid="2.16.840.1.113883.5.107" uri="http://hl7.org/fhir/v3/RoleLinkType"/>
	<convert oid="2.16.840.1.113883.5.1068" uri="http://hl7.org/fhir/v3/RoleStatus"/>
	<convert oid="2.16.840.1.113883.5.113" uri="http://hl7.org/fhir/v3/Sequencing"/>
	<convert oid="2.16.840.1.113883.5.1069" uri="http://hl7.org/fhir/v3/SetOperator"/>
	<convert oid="2.16.840.1.113883.5.139" uri="http://hl7.org/fhir/v3/TimingEvent"/>
	<convert oid="2.16.840.1.113883.5.1111" uri="http://hl7.org/fhir/v3/TransmissionRelationshipTypeCode"/>
	<convert oid="2.16.840.1.113883.6.8" uri="http://hl7.org/fhir/v3/ucum"/>
	<convert oid="2.16.840.1.113883.5.143" uri="http://hl7.org/fhir/v3/URLScheme"/>
</root>
